### ISSUE TITLE
Want to partner combining with past sponsors

### ISSUE THREAD

**Issue by nirmaldalmia** [HackBMU/HackBMU-2.0#5]
Want to partner section is merging with the past sponsors section.
![image](https://user-images.githubusercontent.com/27962178/48465073-a6768380-e807-11e8-987f-9ffd7cddc153.png)

**Comment by GhostBug-007** [comment]
> Want to partner section is merging with the past sponsors section.
> ![image](https://user-images.githubusercontent.com/27962178/48465073-a6768380-e807-11e8-987f-9ffd7cddc153.png)

I think this issue is solved
![screenshot from 2018-11-28 16-15-01](https://user-images.githubusercontent.com/36124252/49146728-c9855500-f328-11e8-8107-f58449840e8f.png)

**Comment by GhostBug-007** [comment]
This is done
